box/urls.py
from . import views
from django.urls import path

app_name = 'box'

urlpatterns = [
	path('',views.MainView.as_view(), name ="main"),
	path('opening/', views.OpeningView.as_view(), name="opening"),
	path('notify', views.AddNotificationView.as_view(), name="notify"),
	path('signup', views.SignupView.as_view(), name="signup"),
	path('unsubscribe/<product__name>', views.remove_notification, name="nopeify")
]

onepiecetcg/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('box.urls')),
    path('home/', include('home.urls')),
    path('draft/', include('draft.urls')),
    #re_path(r'^', include(routing.websocket_urlpatterns))
]

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'static/'),
        }
    ),
]

box/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.

class CardType(models.Model):
	card_type = models.CharField(max_length = 16, default = 'placeholder', null = True)

	def __str__(self):
		return self.card_type

class Rarity(models.Model): #based on pull rates, maybe add many-to-many CardRarity because it can be both parallel and super rare
	rarity = models.CharField(max_length = 32, default = 'placeholder', unique = True)

	def __str__(self):
		return self.rarity


class CardSet(models.Model):
	set_name = models.CharField(max_length = 128, default = 'placeholder', unique  = True)
	set_id = models.CharField(max_length = 16, default = 'placeholder', unique = True)

	def __str__(self):
		return self.set_name

class Card(models.Model):
	name = models.CharField(max_length = 64)
	card_id = models.CharField(max_length = 10)
	marketprice = models.FloatField()
	image_link = models.CharField(max_length = 64)
	#in_stock = models.BooleanField

	card_color = models.ManyToManyField('Color', through='CardColor')
	card_draft = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Draft', related_name='drafted_card')
	card_type = models.ForeignKey(CardType, on_delete=models.CASCADE)
	rarity = models.ForeignKey(Rarity, on_delete=models.CASCADE)
	card_set = models.ForeignKey(CardSet, on_delete=models.CASCADE)

	def __str__(self):
		return "Card Name :" + str(self.name) + " Card ID: " + str(self.card_id)

class Draft(models.Model):
	card_count = models.IntegerField(default=0)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	card = models.ForeignKey(Card, on_delete=models.CASCADE)

class Product(models.Model):
	name = models.CharField(max_length = 100, unique = True)
	marketprice = models.FloatField()
	product_set = models.ForeignKey(CardSet, on_delete= models.CASCADE, default=1)
	user_product = models.ManyToManyField(settings.AUTH_USER_MODEL, through='UserProduct', related_name = 'user_product')

class UserProduct(models.Model):
	price_notifications = models.BooleanField(default = False)
	wanted_price = models.FloatField(default = 0)
	highest_value_opened = models.FloatField(default = 0)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

	class Meta:
		unique_together = ('user', 'product')


class Color(models.Model):
	card_color = models.ManyToManyField('Card', through='CardColor')
	color = models.CharField(max_length = 12, null = True)

	def __str__(self):
		return self.color

class CardColor(models.Model):
	card = models.ForeignKey(Card, on_delete=models.CASCADE)
	color = models.ForeignKey(Color, on_delete=models.CASCADE)


#class CustomCard(models.Model):
#	name = models.CharField(max_length = 64)
#	attribute = something
#	power = 

box/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm  


class SignupForm(UserCreationForm):
	email = forms.EmailField(label='email')

box/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import CreateView
from django.urls import reverse_lazy, reverse
from django.conf import settings
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm  
from django.contrib.auth.mixins import LoginRequiredMixin

from box.methods import get_average, get_minimum, get_random_packs
from box.models import Product, UserProduct
from box.forms import SignupForm

def my_callback(sender):
	print("something happens")
	
class MainView(View):
	def get(self, request):
		chosen_set = 'Romance Dawn'
		average_box_value = get_average(chosen_set)
		minimal_box_value = get_minimum(chosen_set)

		cntx = {
				'average_box_value' : average_box_value,
				'minimal_box_value' : minimal_box_value,
				}

		return render(request, 'box/main.html', cntx)#reverse dodaj


class AddNotificationView(LoginRequiredMixin, View):
	def get(self, request):#figure out why cardset doesn't work right
		notify_list = UserProduct.objects.filter(user=request.user, price_notifications=True).values('product__name', 'wanted_price')
		product_list = Product.objects.exclude(product_set = 24).values('name', 'marketprice').order_by('name')#exclude promo karte

		cntx = {
				'product_list' : product_list,
				'notify_list':notify_list
				}

		return render(request, 'box/notify.html', cntx)

	def post(self, request):
		product = get_object_or_404(Product, name=request.POST['tracked_product'])
		up, created = UserProduct.objects.get_or_create(user=request.user, product=product)

		if not created:
			up.wanted_price = request.POST['wanted_price']
			up.price_notifications = True
			up.save()

		else:
			up.price_notifications = True
			up.wanted_price = request.POST['wanted_price']
			up.save()

		return redirect(reverse_lazy('box:notify'))


def remove_notification(request, product__name):
	product = get_object_or_404(Product, name=product__name)#vjerojatno postoji način da se referiram na to u notificationu
	notification = get_object_or_404(UserProduct, user=request.user, product=product)
	notification.price_notifications = False
	notification.wanted_price = 0
	notification.save()
	return redirect(reverse_lazy('box:notify'))


class OpeningView(View):
	def get(self, request, chosen_set = None, number_of_packs = None):
		if number_of_packs == None:
			number_of_packs = 24
		else:
			number_of_packs = int(number_of_packs)

		if chosen_set == None:
			chosen_set = 'Romance Dawn'
		
		number_of_packs = int(request.GET.get('number_of_packs', number_of_packs))
		random_packs = get_random_packs(chosen_set, number_of_packs)

		card_list = random_packs['card_list']
		total_value = random_packs['total_value']
		card_count = len(card_list)

		highest_ever = UserProduct.objects.values('highest_value_opened').order_by('-highest_value_opened')[0]

		cntx = {
				'card_list' : card_list,
				'card_count' : card_count,
				'total_value' : total_value,
				'highest_ever': highest_ever['highest_value_opened'],
				}

		if request.user.is_anonymous is False:#vjerojatno ima bolji način
			product_opened = get_object_or_404(Product, name=f'{chosen_set} Booster Box')
			current_highest, created = UserProduct.objects.get_or_create(user=request.user, product=product_opened)
			if current_highest.highest_value_opened < total_value:
				current_highest.highest_value_opened = total_value
				current_highest.save()
			cntx['highest_value'] = current_highest.highest_value_opened

		return render(request, 'box/opening.html', cntx)


class SignupView(CreateView):
	model = User
	success_url = reverse_lazy('box:main')
	template_name = 'registration/signup.html'

	def get(self, request):
		form = SignupForm()
		context = {'form':form}
		return render(request, self.template_name, context)

	def post(self, request):
		form = SignupForm(request.POST)
		if not form.is_valid():
			return render(request, self.template_name, {'form':form})

		new_user = form.save()
		new_user = authenticate(username=form.cleaned_data['username'],
								password=form.cleaned_data['password1'],)
		login(request, new_user)

		return redirect(self.success_url)

#class CreateCard(View):

#23 DON!!
#1 box topper
#1 alternate DON
#168 common
#72 uncommon - 8 leader = 64 uncommon
#24 rare - 8.34 super rare or greater = 15.66 rare
#1 parallel
#0.67 secret rare 
#0.33 alternate leader 
#0.0083 manga

#nadogradnje
#pack opening-box opening, highest value box opened on site
#draft? imam random_packs
#auto-update baze podataka jednom dnevno
#notify mailom kad x karta ili box value padne ispod unesenih podataka
#hover iznad prouvoda u notify prikaže sliku
#list of cards, ability to search and filter 
#zasebna baza koja prati dnevno kretanje (vjerojatno u jsonu)
#createa-a-card

box/templates/box/main.html
{% extends "base_menu.html" %}
{% block content %}
<div>
<h1>BOX AVERAGE MARKET VALUE </h1>
<p>WORK IN PROGRESS
<p>The average value of pulls from a box is {{ average_box_value }}</p>
<p>The minimal value of pulls from a box is {{ minimal_box_value }}</p>

</div>
{% endblock %}

box/templates/box/notify.html
{% extends "base_menu.html" %}
{% block content %}
<div>
{% for product in notify_list %}
<p>You'll be notified by email when {{ product.product__name }} reaches the price of {{ product.wanted_price }}$
<a href="{% url 'box:nopeify' product.product__name %}"> (unsubscribe)</a>
</p>
{% endfor %}
<form method="post" action="">
{% csrf_token %}
{{ form.as_p }}
<label for="set_price">Wanted Price</label>
<input type="number" id="set_price" name="wanted_price" /><br>
{% for product in product_list %}
<input type="radio" id="product_name" name="tracked_product" value="{{ product.name }}" />
<label for="product_name">{{ product.name }} || {{ product.marketprice }}$</label><br>
{% endfor %}
<input type="submit" class="btn btn-primary" value="Notify me" />
</form>
</div>
{% endblock %}

box/templates/box/opening.html
{% extends "base_menu.html" %}
{% block content %}

<style>
.main-container {
  display: flex;
  flex-wrap: wrap;
}

.card-container {
    width: 10%;
    margin: 10px;
}

.card-image {
    width: 100%;
}

.card-text {
    padding: 10px;
}
</style>

<div>
<p> highest value ever opened is {{ highest_ever }}</p>
{% if user.is_authenticated %}
<p> highest value you've opened is {{ highest_value }}</p>
{% endif %}
<p> value of cards opened is {{ total_value }}</p>
<form action="{% url 'box:opening' %}" method="get">
<label for="set">Romance Dawn</label>
<input type="radio" id="set" name="set" value="Romance Dawn"><br>
<input type="number" id ="number_of_packs" name="number_of_packs" min="1" max="24" step="1" value="24" />
<input type="submit" class="btn btn-primary" value="Open Packs" /></a>
</form>

<div class="main-container">
{% for card in card_list %}
<div class="card-container">
  <img src={{ card.image_link }}  alt="example image" class="card-image">
  <div class="card-text">
    <p>{{ card.count }}x {{ card.name }}</p>
    <p>{{ card.card_id }}</p>
    <p>{{ card.marketprice }}$</p>
  </div>
 </div>
{% endfor %}
</div>
{% endblock %}