box/urls.py
from . import views
from django.urls import path

app_name = 'box'

urlpatterns = [
	path('',views.MainView.as_view(), name ="main"),
	path('opening/', views.OpeningView.as_view(), name="opening"),
	path('notify', views.AddNotificationView.as_view(), name="notify"),
	path('signup', views.SignupView.as_view(), name="signup"),
	path('unsubscribe/<product__name>', views.remove_notification, name="nopeify")
]

draft/urls.py
from django.urls import path
from . import views

app_name = 'draft'
urlpatterns = [
	path('lobby', views.lobby, name="lobby"),
	path('lobby/<str:room_name>/', views.asynclobby, name="alobby"),
	path('lobby/<str:room_name>/add', views.add_card, name="add_card")


]

home/urls.py
from . import views
from django.urls import path

app_name = 'home'

urlpatterns = [

]

onepiecetcg/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('box.urls')),
    path('home/', include('home.urls')),
    path('draft/', include('draft.urls')),
    #re_path(r'^', include(routing.websocket_urlpatterns))
]

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'static/'),
        }
    ),
]

home/views.py
from django.shortcuts import render

# Create your views here.

home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->
<meta name="dj4e" content="b14306cd6ce646b9b7bee6ea942711a1">

<meta name="dj4e-code" content="42166279059306">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2022-09-01">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

home/templates/base_menu.html
{% extends "base_bootstrap.html" %}
{% block navbar %}

<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">
      {% url 'ads' as ads %}
      <li {% if request.get_full_path == ads %}class="active"{% endif %}>
          <a href="{% url 'box:main' %}">ONE PIECE TCG</a></li>
    </ul>
   
    <ul class="nav navbar-nav navbar-right">
        <li>
        <a href="{% url 'draft:lobby' %}">Draft</a>
        </li>
        <li>
        <a href="{% url 'box:opening' %}">Open Packs</a>
        </li>
        <li>
        <a href="{% url 'box:notify' %}">Notify me!</a>
        </li>
                {% if user.is_authenticated %}
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                <img style="width: 25px;" src=""/><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'logout' %}?next={% url 'box:main' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'login' %}?next={% url 'box:main' %}">Login</a>
    </li>
    <li>
        <a href="{% url 'box:signup' %}?next={% url 'box:main' %}">Sign up</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}